apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-config
data:
  logstash.conf: |
    input {
      tcp {
        port => 5044
        codec => json
      }
    }

    filter {
      mutate {
        rename => { "log" => "message" }
      }
      mutate {
        remove_field => ["date", "host"]
      }
    }

    output {
      elasticsearch {
        hosts => ["http://elasticsearch:9200"]
        index => "kubernetes-logs-%{+YYYY.MM.dd}"
      }
    }
